### ISSUE TITLE
Press Freedom Analysis

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/ML-Crate#274]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Press Freedom Analysis
:red_circle: **Aim** : Analyse the freedom of press in different aspects.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/mfaaris/press-freedom-index-and-abuse
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Asttttha** [comment]
Full name : Astha Samaddar
GitHub Profile Link : https://github.com/Asttttha
Participant ID (If not, then put NA) : NA
Approach for this Project : To analyse various columns of this dataset.
What is your participant role? HRSoC 2022 Participant

**Comment by abhisheks008** [comment]
Hey Astha, thanks for choosing ML-Crate. Issue assigned to you :rocket:

**Comment by abhisheks008** [comment]
Updates please @Asttttha

**Comment by Asttttha** [comment]
> Updates please @Asttttha

Still working on it

**Comment by abhisheks008** [comment]
Okay. Carry on 🚀 @Asttttha

**Comment by abhisheks008** [comment]
Please complete the issue before the deadline @Asttttha

**Comment by abhisheks008** [comment]
Great one to work on. Issue assigned to you @Shruti1921. Go ahead!

**Comment by abhisheks008** [comment]
Issue has been un-assigned from you due to inactivity.
@Shruti1921

**Comment by swadhin1237** [comment]
Full name : Swadhin Satyaprakash Majhi
GitHub Profile Link : https://github.com/swadhin1237
Participant ID (If not, then put NA) : NA
Approach for this Project : To analyse the dataset and make proper EDA with visualization.
What is your participant role?KWOC 22 participants.

**Comment by abhisheks008** [comment]
Issue assigned to you @swadhin1237
