### ISSUE TITLE
Credit Score Classification

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/ML-Crate#317]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Credit Score Classification
:red_circle: **Aim** : Classify the credit scores of different customers.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/parisrohan/credit-score-classification
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Karanshelke** [comment]
Full name : Karan Shelke
GitHub Profile Link : https://github.com/Karanshelke
Participant ID (If not, then put NA) : Saurabhbangar0
Approach for this Project : We'll try different algorithms and try to find best one
What is your participant role?

**Comment by Shruti1921** [comment]
Full Name: Shruti Pawar
GitHub Profile Link: https://github.com/Shruti1921
Participant ID: NA
Approach: I will try to use 3-4 algorithms to implement the credit score classification model and perform exploratory data analysis before creating model

Please assign this issue to me...

**Comment by Diksha2602** [comment]
Hello I would like to work on this project. Please assign it to me
Full name :Diksha Bhusare
GitHub Profile Link :https://github.com/Diksha2602
Participant ID (If not, then put NA) : NA
Approach for this Project : I would first perform Data Collection & Processing, Data Analysis then Splitting the data into training data & Test data Handling the Missing values. Then Converting the Category into numeric, build the Model, importing the Test Data and predicting the Values from Models.
What is your participant role? - Contributor

**Comment by abhisheks008** [comment]
@Shruti1921 and @Diksha2602 both of you have commented here for taking up the issue. But the approach given by @Diksha2602 sounds really good to me. Hence, @Diksha2602 issue assigned to you.

@Shruti1921 One thing I can suggest, while taking up any issue in any open source repo, please keep that in mind, that you need to be specific enough with your approach, b'coz in those highly rated repos, everyone is pushing themselves to get the issue assigned. You need to elaborate and clarify the approach, which makes you stand out among the others. As a result you will get the issue assigned. Hope you understand. In my repos, you can check out other issues there in this repo. Best wishes & Happy Diwali.

**Comment by Shruti1921** [comment]
Thank you for the suggestion. I will try to keep my request more approachable so that the issue will get assigned to me in the future.
