### ISSUE TITLE
Soil Moisture Prediction

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/ML-Crate#337]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Soil Moisture Prediction
:red_circle: **Aim** : This project will help us in predicting the moisture of the soil to check if it's wet or dry
:red_circle: **Dataset** : https://www.kaggle.com/amirmohammdjalili/soil-moisture-dataset
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avik-creator** [comment]
@abhisheks008 Do we need to use TensorFlow in it?

**Comment by Var69** [comment]
Please assign me this issue

**Comment by abhisheks008** [comment]
Please share your approach and follow the issue template, comment accordingly.
@Var69

**Comment by Var69** [comment]
> Please share your approach and follow the issue template, comment accordingly. @Var69

Full name : Varun Nair
GitHub Profile Link: https://github.com/Var69
Participant ID (If not, then put NA) : NA
Approach for this Project:  TrI will use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitting algorithm for the model by checking the accuracy scores. I will also do an exploratory data analysis before creating any model.

**Comment by Var69** [comment]
I have sent pull request pls evaluate.

**Comment by abhisheks008** [comment]
Issue has been un-assigned from you due to inactivity.
@Var69

**Comment by riitikiitkgp** [comment]
Full name : Ritik Kumar
GitHub Profile Link: https://github.com/riitikiitkgp
Participant ID (If not, then put NA) : NA
Approach for this Project: Will use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitting algorithm for the model by checking the accuracy scores. I will also do an exploratory data analysis before creating any model.

**Comment by swadhin1237** [comment]
Full name : Swadhin Satyaprakash Majhi
GitHub Profile Link: https://github.com/swadhin1237 
Participant ID (If not, then put NA): NA
Approach for this Project: Will use 3-4 algorithms such as SVM and ANN to implement the models and compare all the algorithms to find out the best fitting algorithm for the model by checking the accuracy scores. I will also do an exploratory data analysis before creating any model.
What is your participant role? Contributor in KWOC 22

**Comment by abhisheks008** [comment]
Based on FCFS basis, @riitikiitkgp issue assigned to you.
@swadhin1237 you can look after for different issues.
