### ISSUE TITLE
Cancer Analysis based on Chernobyl Event

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/ML-Crate#391]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Cancer Analysis based on Chernobyl Event
:red_circle: **Aim** : The aim to create a Data Analysis project which will help us to understand the cancer rates among the people of Chernobyl before and after the event.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/marshuu/cancer-rate-before-and-after-chernobyl
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by swadhin1237** [comment]
Hello, I would like to work on this project. Please assign it to me
Full Name: SWADHIN SATYAPRAKASH MAJHI
GitHub Link: https://github.com/swadhin1237
Participant ID: NA
Approach For this project: I will try to use 2-4 algorithms to implement the models and compare all the algorithms to find out the best fitting algorithm for the model by checking the accuracy scores. Also, I will perform an exploratory data analysis before creating any model.
What is your participant role: contributor

**Comment by abhisheks008** [comment]
You are not a participant from KWOC 2022 right?
@swadhin1237

**Comment by swadhin1237** [comment]
No I'm taking part in KWOC but do not know how to get participant ID?

**Comment by abhisheks008** [comment]
Got it. Issue assigned to you @swadhin1237. Go ahead!

**Comment by swadhin1237** [comment]
Thank you
