### ISSUE TITLE
Smartphone Brands Analysis

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/ML-Crate#399]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Smartphone Brands Analysis
:red_circle: **Aim** : Create a data analysis project which analyze different mobile brands.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/shreyamishra0307/top-5-mobile-brands-amazon-dataset
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by p1utoze** [comment]
Hi, I'm Adithya Awati.
I want to take up this issue. Can you assign it to me?
https://github.com/p1utoze

**Comment by swadhin1237** [comment]
Hello, I would like to work on this project. Please assign it to me
Full Name: SWADHIN SATYAPRAKASH MAJHI
GitHub Link: https://github.com/swadhin1237
Participant ID: NA
Approach For this project: I will try to use 2-4 algorithms to implement the models and compare all the algorithms to find out the best fitting algorithm for the model by checking the accuracy scores. Also, I will perform an exploratory data analysis before creating any model.
What is your participant role: contributor

**Comment by ManasviEmmadi** [comment]
Hello! I want to contribute to this project for KWoC '22. Would be great if you could assign it to me.
Full name : Manasvi Emmadi
GitHub Link: https://github.com/ManasviEmmadi
Participant ID: NA
Approach For this project: I will perform EDA and display it using different graphs. Would use different ensemble techniques for getting the best accuracy score.
What is your participant role: contributor KWoC '22
