### ISSUE TITLE
Car image classifier

### ISSUE THREAD

**Issue by PARKER-X** [World-of-ML/ML-Crate#417]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Car Image Classifier
:red_circle: **Aim** : classify car images
:red_circle: **Dataset** : https://www.kaggle.com/datasets/lucifierx/car-image-classification
:red_circle: **Approach** : Use cnn model to classify car 

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Harsh
- GitHub Profile Link : http://github.com/PARKER-X
- Participant ID (If not, then put NA) : NA
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) Kwoc

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by inamdarketan** [comment]
Please assign this task to me.
